# Generated by Django 5.2.4 on 2025-08-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=150)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='description',
            new_name='story_line',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='title',
        ),
    ]
