# Generated by Django 5.2.4 on 2025-08-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
